# Generated by Django 4.2.7 on 2023-12-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
